[formatting]
align_comments        = false
align_entries         = true
allowed_blank_lines   = 1
array_auto_collapse   = true
array_auto_expand     = true
array_trailing_comma  = true
column_width          = 80
compact_arrays        = true
compact_entries       = false
compact_inline_tables = false
crlf                  = false
indent_entries        = false
indent_string         = "  "
indent_tables         = false
inline_table_expand   = true
reorder_inline_tables = false
reorder_keys          = true
trailing_newline      = true
