#!/usr/bin/env bash

set -euo pipefail

THISDIR="$(dirname "$(readlink -f "$0")")"

DEBUG=${DEBUG:-}

DRY_RUN=false


if [[ $DEBUG -eq 2 ]]; then set -x; fi


_validate_bin() {
  for dep in "$@"; do command -v "$dep" >/dev/null \
    || { echo >&2 "Missing required dependency: $dep"; exit 1; }
  done; unset dep
}

_validate_bin fd gum jq ln rg sd taplo


__debug() { test -z "$DEBUG" || gum log -tRFC1123Z -ldebug -s "$@"; }


_find_config() {
  local file="${DOTFILES_CONFIG_FILE:-}"
  if [[ -z "$file" ]]; then
    if [[ -f "$THISDIR/.secret/dotfiles.toml" ]]; then
      file="$THISDIR/.secret/dotfiles.toml"
    else
      file="$THISDIR/dotfiles.toml"
    fi
  fi
  printf '%s' "$file"
}

DOTFILES_CONFIG="$(_find_config)"

if [[ ! -f "$DOTFILES_CONFIG" ]]; then
  printf '%s' "error: $DOTFILES_CONFIG not found." | gum >&2 style --foreground='#dc4720'
  exit 1
fi

CONFIG="$(
	eval "cat <<-EOF
	$(<"$DOTFILES_CONFIG")
	EOF" | taplo get -ojson | jq
)"


declare -a LN_OPTS
ln --help | rg '\-a,\s+--absolute' &>/dev/null && LN_OPTS+=(-a)
ln --help | rg '\-f,\s+--force' &>/dev/null && LN_OPTS+=(-f)
LN_OPTS+=(-s)


IGNORE_PATTERNS=(-E '.ignore/' -E '.templates/' -E '.gitignore' -E 'README.md')


_create_or_replace_symlink() {
  src_file="$(realpath "$1")"
  # Make the directory first in the case it's an old symlink source,
  # otherwise realpath will fail in the following command.
  mkdir -p "$(dirname "$2")"
  dest_file="$(realpath --no-symlinks "$2")"

  __debug "src_file=$src_file"
  __debug "dest_file=$dest_file"

  # Delete if destination alredy exists as a regular file.
  if [[ -f "$dest_file" ]] && [[ ! -L "$dest_file" ]]; then
    rm "$dest_file"
  fi

  # Verify an existing symlink points to the correct source, fix if not.
  if [[ -L "$dest_file" ]]; then
    if [[ "$(realpath -m "$dest_file")" != "$(realpath "$src_file")" ]]; then
      printf '%s' "Canonical path of $dest_file does not exist. Replacing symlink source." \
       | gum style --foreground='#FCFA7D'

      rm -f "$dest_file"
    fi
  fi

  dest_dir="$(dirname "$dest_file")"

  mkdir -p "$dest_dir"

  if sudo="$(command -v sudo)"; then
    "$sudo" ln "${LN_OPTS[@]}" "$src_file" "$dest_file" >/dev/null 2>&1 || true
  else
    ln "${LN_OPTS[@]}" "$src_file" "$dest_file" >/dev/null 2>&1 || true
  fi

  # option to exit if symlink failed
  if [[ ! -L "$dest_file" ]]; then
    if gum confirm "failed to symlink file $src_file > $dest_file. Continue or exit script?"; then
      exit 1
    fi
  else
    printf '%s' "1 file linked: $src_file -> $dest_path" \
     | gum style --bold --foreground='#89F57C' 
  fi
}


_create_or_replace_symlink_dry_run() {
  src_file="$(realpath "$1")"
  dest_file="$(realpath -m --no-symlinks -- "$2")"

  __debug "src_file=$src_file"
  __debug "dest_file=$dest_file"

  # if dest file exists and is not a symlink
  if [[ -f "$dest_file" ]] && [[ ! -L "$dest_file" ]]; then
    printf '%s' \
    "Would delete existing destination file: $dest_file." \
    | gum style --foreground='#6C6CDF'
  fi

  if [[ -L "$dest_file" ]]; then
    if [[ "$(realpath -m "$dest_file")" != "$(realpath "$src_file")" ]]; then
      printf '%s' "Canonical path of $dest_file does not exist. Replacing symlink source." \
        | gum style --foreground='#FCFA7D'
    fi
  fi

  dest_dir="$(dirname "$dest_file")"

  if [[ ! -d "$dest_dir" ]]; then
    printf '%s' "Would create directory: $(dirname "$dest_file")" \
      | gum style --foreground='#6C6CDF'
  fi

  printf '%s' "Would link 1 file: $src_file -> $dest_path" \
   | gum style --bold --foreground='#89F57C' 
}


_replace_patterns() {
  local key T object pattern replacement
  key="$1"; T="$2"

  for (( i=0; i<"$(jq '. | length' <<< "$T")"; i++ )); do
    object="$(jq -r ".[$i]" <<< "$T")"
    pattern="$(jq -r ".pattern" <<< "$object")"
    replacement="$(jq -r ".replacement" <<< "$object")"

    __debug "pattern=$pattern"
    __debug "replacement=$replacement"

    fd -ua --print0 --base-directory "$(realpath "./$key/.templates/")" -tf | xargs -0 sd -F "$pattern" "$replacement"
  done
}


_expand_user() { echo "${1/#\~/$HOME}"; }


_deploy_files() {
  if [[ ! -d "$1" ]]; then
    gum style --faint >&2 "The base directory path '$1' is not a directory. Skipping"
    return
  fi

  local key key_object templates files patterns_file

  key="${1%/}"
  fd_filter="${2:-}"
  key_object="$(jq ".\"$key\"" <<< "$CONFIG")"
  templates="$(jq '.templates // empty' <<< "$key_object")"
  files="$(jq -r '.files // empty' <<< "$key_object")"

  patterns_file="$(mktemp -t tmp.dotfiles.patterns.XXXXXXXXXX)"
  if [[ -n "$templates" ]]; then
    jq -r '.[].pattern' <<< "$templates" | sort -u > "$patterns_file"
  fi

  fd_opts=(--unrestricted --type file --full-path --base-directory "$key")
  readarray -t file_list < <(fd "${fd_opts[@]}" "${IGNORE_PATTERNS[@]}" "$fd_filter")
  readarray -t config_file_list < <(jq 'keys | .[]' -r <<< "$files")

  if [[ "${#config_file_list[@]}" -eq 0 ]]; then
    gum style --faint >&2 "$key has no files defined in config. Skipping.."
    return
  fi

  for file in "${file_list[@]}"; do
    # Skip files that start with 2 leading underscores.
    if [[ $file =~ ^__.* ]]; then
      continue
    # Skip files found without any entry in config.
    elif [[ ! " ${config_file_list[*]} " =~ [[:space:]]${file}[[:space:]] ]]; then
      gum style --faint >&2 \
        "$file found in dir $key/ but no destination path set in config. Skipping file.."
      continue
    else
      src_path=$key/$file
      dest_prefix="$(_expand_user "$(jq -r ".\"$file\"" <<< "$files")")"

      if jq '. | type == "array"' <<< "$dest_prefix" &>/dev/null; then
        gum log -tRFC1123Z -lerror >&2 \
          "linking a file to a multiple destinations not implemented yet: $src_path = $dest_prefix"
        exit 1
      fi

      target_file_name="$(basename "$file")"
      # if destination string doesn't end in '/', and doesn't already exist as a directory,
      # treat the final path segment as the destination file name,
      # and use the parent directory as the destination prefix.
      if [[ ! "$dest_prefix" =~ /$  && ! -d "$dest_prefix" ]]; then
        target_file_name="$(basename "$dest_prefix")"
        dest_prefix="$(dirname "$dest_prefix")"
      fi

      dest_path="${dest_prefix%/}/$target_file_name"

      # If file contains a pattern from dotfiles.toml, copy the file to the
      # local .templates/ dir and apply the substitutions.
      # Reassign src_path to the new template file and symlink that instead.
      if [[ -n "$templates" ]] && [[ -n "$(rg -Ff "$patterns_file" "$src_path")" ]]; then
        template_dir="$key/.templates"
        template_file="$template_dir/$file"

        mkdir -p "$template_dir"

        if ! "$DRY_RUN"; then
          cp --preserve=all --force "$src_path" "$template_file" \
            2> >(gum log -tRFC1123Z -lerror "$@" 2>/dev/null)
        else
          printf '%s' "Would copy file $src_path to template dir $template_dir" \
           | gum style --foreground='#FCFA7D'
        fi

        src_path="$template_file"
      fi

      if ! "$DRY_RUN"; then
        _create_or_replace_symlink "$src_path" "$dest_path"
      else
        _create_or_replace_symlink_dry_run "$src_path" "$dest_path"
      fi
    fi
  done

  rm -f "$patterns_file"

  if [[ -n "$templates" ]]; then
    if ! "$DRY_RUN"; then
      _replace_patterns "$key" "$templates";
    # else
      # TODO: show expected templated file
    fi
  fi

  return 0
}


usage() {
	cat <<- EOF
	Usage: ${BASH_SOURCE[0]} [OPTIONS] [ARGS]
	
	Examples:
	\$ ${BASH_SOURCE[0]} 

	\$ DEBUG=1 ${BASH_SOURCE[0]}

	\$ ${BASH_SOURCE[0]} --fd-filter git -- bin
	\$ ${BASH_SOURCE[0]} -fgit -- bin

	Options:
	  -h, --help       Display this help message.
	  -d, --dry-run    Templated files will still be copied, but no symlink targets are created.
	  -f, --fd-filter  Filter to pass to fd when searching for files.
	EOF
}


main() {
  declare -a DIRS

  FD_FILTER=

  GETOPT_ARGS=(--options 'hdf:' --long 'help,dry-run,fd-filter:')

  if OPTS=$(getopt "${GETOPT_ARGS[@]}" -- "$@"); then eval set -- "$OPTS"; fi

  while :; do
    case "$1" in
      -h | --help)       usage; exit 0 ;;
      -f | --fd-filter)  FD_FILTER="$2"; shift ;;
      -d | --dry-run)    export DRY_RUN=true;;
      --)                shift; break ;;
      *)                 echo >&2 'error'; exit 1 ;;
    esac
    shift
  done

  DIRS=("$@") # remaining args

  if [ ${#DIRS[@]} -eq 0 ]; then
    # If no args passed, read top-level keys from config.
    readarray -t DIRS < <(jq -r '. | keys | .[]' <<< "$CONFIG")
    # Reversing order of the array, so it reads top -> bottom of the config file.
    __reverse_array_order() { DIRS=("${BASH_ARGV[@]}"); }
    shopt -s extdebug
    __reverse_array_order "${DIRS[@]}"
    shopt -u extdebug
  fi

  "$DRY_RUN" && printf '%s %s' \
    'dry run is enabled, templated files will still be copied' \
    'but no symlink targets will be created.' \
    | gum style --italic --foreground='#8FFAFD'

  for d in "${DIRS[@]}"; do
    _deploy_files "$(tr -d '\r' <<< "$d")" "$FD_FILTER"
  done; unset d

  exit 0
}


main "$@"
