"$schema" = "https://starship.rs/config-schema.json"

format       = "$all $fill $time$line_break$jobs$status$container$shell$character"
right_format = ""

add_newline     = true
command_timeout = 300000
follow_symlinks = true
scan_timeout    = 30

[character]
success_symbol = "[➜ ](bold green)"

[direnv]
disabled = false

[status]
disabled = false

[gcloud]
detect_env_vars = ["CLOUDSDK_CONFIG"]
disabled        = false


[gcloud.region_aliases]
asia-northeast1         = 'an1'
northamerica-northeast1 = 'ne1'
us-central1             = 'uc1'
us-west1                = 'uw1'
[fill]
style  = "bold black"
symbol = "."

[time]
disabled        = false
format          = "[$time]($style) "
style           = "bold #f0f0ff"
time_format     = "%T"
utc_time_offset = "local"

[shell]
disabled = false

[memory_usage]
disabled  = false
format    = 'via $symbol[${ram_pct}( | ${swap_pct})]($style) '
style     = 'bold dimmed white'
symbol    = ''
threshold = -1

[git_metrics]
disabled = false
format   = '[+$added]($added_style)/[-$deleted]($deleted_style) '
