"$schema" = "https://starship.rs/config-schema.json"

add_newline     = true
command_timeout = 300000
follow_symlinks = true
format          = "$all$fill $time$line_break$jobs$status$container$shell$character"
right_format    = ""
scan_timeout    = 30

[character]
error_symbol   = '[](bold red)'
success_symbol = '[](bold green)'

[cmd_duration]
min_time          = 500
show_milliseconds = true

[direnv]
disabled = false

[status]
disabled              = false
format                = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol            = true
not_executable_symbol = " "
not_found_symbol      = "󱉶 "
pipestatus            = true
pipestatus_format     = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int]($style) '
sigint_symbol         = " "
signal_symbol         = "󱐋 "
symbol                = " "

[gcloud]
detect_env_vars = ["CLOUDSDK_CONFIG"]
format          = "on [$project:$account@$domain]($style) "

[fill]
style  = "bold black"
symbol = "."

[time]
disabled        = false
format          = "[$time]($style) "
style           = "bold #f0f0ff"
time_format     = "%T"
utc_time_offset = "local"

[git_metrics]
disabled = false
format   = "[+$added]($added_style)/[-$deleted]($deleted_style) "

[git_commit]
only_detached = false
tag_disabled  = false
tag_symbol    = '  '

[memory_usage]
disabled  = true
format    = "via $symbol[${ram_pct}( | ${swap_pct})]($style) "
style     = "bold dimmed white"
symbol    = "󰍛 "
threshold = -1

[directory]
read_only         = " 󰌾"
truncation_length = 3
use_os_path_sep   = false

[directory.substitutions]
'A:' = '/a'
'B:' = '/b'
'C:' = '/c'
'D:' = '/d'
'E:' = '/e'
'F:' = '/f'
'G:' = '/g'
'H:' = '/h'
'I:' = '/i'
'J:' = '/j'
'K:' = '/k'
'L:' = '/l'
'M:' = '/m'
'N:' = '/n'
'O:' = '/o'
'P:' = '/p'
'Q:' = '/q'
'R:' = '/r'
'S:' = '/s'
'T:' = '/t'
'U:' = '/u'
'V:' = '/v'
'W:' = '/w'
'X:' = '/x'
'Y:' = '/y'
'Z:' = '/z'

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
AlmaLinux        = " "
Alpaquita        = " "
Alpine           = " "
Amazon           = " "
Android          = " "
Arch             = " "
Artix            = " "
CentOS           = " "
Debian           = " "
DragonFly        = " "
Emscripten       = " "
EndeavourOS      = " "
Fedora           = " "
FreeBSD          = " "
Garuda           = "󰛓 "
Gentoo           = " "
HardenedBSD      = "󰞌 "
Illumos          = "󰈸 "
Kali             = " "
Linux            = " "
Mabox            = " "
Macos            = " "
Manjaro          = " "
Mariner          = " "
MidnightBSD      = " "
Mint             = " "
NetBSD           = " "
NixOS            = " "
OpenBSD          = "󰈺 "
OracleLinux      = "󰌷 "
Pop              = " "
Raspbian         = " "
RedHatEnterprise = " "
Redhat           = " "
Redox            = "󰀘 "
RockyLinux       = " "
SUSE             = " "
Solus            = "󰠳 "
Ubuntu           = " "
Unknown          = " "
Void             = " "
Windows          = "󰍲 "
openSUSE         = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
