"$schema" = "https://starship.rs/config-schema.json"

format       = "$all $fill $time$line_break$jobs$status$container$shell$character"
right_format = ""

add_newline     = true
command_timeout = 300000
follow_symlinks = true
scan_timeout    = 30

[character]
success_symbol = "[➜ ](bold green)"

[directory]
use_os_path_sep = false

[direnv]
disabled = false

[status]
disabled = false

[gcloud]
detect_env_vars = ["CLOUDSDK_CONFIG"]
format          = "on [$project:$account@$domain]($style) "

[fill]
style  = "bold black"
symbol = "."

[time]
disabled        = false
format          = "[$time]($style) "
style           = "bold #f0f0ff"
time_format     = "%T"
utc_time_offset = "local"

[git_metrics]
disabled = false
format   = "[+$added]($added_style)/[-$deleted]($deleted_style) "

[git_commit]
only_detached = false
tag_disabled  = false

[memory_usage]
disabled  = true
format    = "via $symbol[${ram_pct}( | ${swap_pct})]($style) "
style     = "bold dimmed white"
symbol    = ""
threshold = -1
