call_parentheses          = "None"
collapse_simple_statement = "FunctionOnly"
column_width              = 100
indent_type               = "Spaces"
indent_width              = 2
line_endings              = "Unix"
quote_style               = "AutoPreferDouble"

[sort_requires]
enabled = true
