array_width                 = 50
attr_fn_like_width          = 50
brace_style                 = "PreferSameLine"
chain_width                 = 50
color                       = "Always"
edition                     = "2024"
empty_item_single_line      = true
fn_call_width               = 60
fn_params_layout            = "Compressed"
fn_single_line              = true
format_code_in_doc_comments = true
format_generated_files      = false
format_macro_bodies         = true
format_macro_matchers       = true
format_strings              = false
group_imports               = "StdExternalCrate"
hard_tabs                   = false
imports_granularity         = "Crate"
imports_indent              = "Visual"
imports_layout              = "Horizontal"
newline_style               = "Unix"
normalize_comments          = true
normalize_doc_attributes    = false
reorder_imports             = true
reorder_modules             = true
space_after_colon           = true
style_edition               = "2024"
tab_spaces                  = 4
trailing_semicolon          = true
unstable_features           = true
use_field_init_shorthand    = true
use_small_heuristics        = "Max"
use_try_shorthand           = true
wrap_comments               = true
