[formatting]
align_comments      = true
allowed_blank_lines = 1
array_auto_collapse = false
array_auto_expand   = true
crlf                = false
indent_string       = "    "
trailing_newline    = true

[[rule]]
include = [".taplo.toml"]

[rule.formatting]
align_entries = true
