#!/usr/bin/env python

import atexit
from contextlib import suppress
from pathlib import Path

try:
    import readline
except ImportError:
    ...
else:
    history: Path = Path.home() / ".cache" / "python" / ".history"

    history.touch(exist_ok=True)

    if not history.read_text(encoding="utf-8"):
        history.write_text("# History created.\n", encoding="utf-8")

    with suppress(OSError):
        readline.read_history_file(history)

    def write_history() -> None:
        with suppress(OSError):
            readline.write_history_file(history)

    atexit.register(write_history)
